### ISSUE TITLE
compose result not working in 1.2.0-beta.0 version

### ISSUE THREAD

**Issue by ashu326** [mvp-rockets/lib-core#3]
it gives internal server error when using composeResult

`ApiError {
  code: 500,
  error: TypeError: Cannot read properties of null (reading 'update')
      at /home/ashutosh/aris_infra/functions/resources/requirements/queries/update-requirement-query.js:12:36
      at processTicksAndRejections (node:internal/process/task_queues:96:5),
  errorMessage: 'Failed to create requirement!',
  errorDescription: 'Internal Server Error'
}
`

**Comment by mangal-napses** [comment]
closing the issue as fixed in newer version
